version: '3.4'
services:
  api:
    container_name: goldberg_api
    build: 
        context: ..
        dockerfile: ./env/api.Dockerfile
        args:
          - UID=${UID:-1000}
          - GID=${GID:-1000}
    restart: unless-stopped
    ports: 
      - 11000:80
    volumes:
      - ../api:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - mysql
    networks:
      - goldberg_network
      - rabbitmq

  client:
    container_name: goldberg_client
    build: 
      context: ..
      dockerfile: ./env/client.Dockerfile
    restart: unless-stopped
    ports:
      - 12000:4321
    volumes:
      - ../client:/app
      - client_node_modules:/app/node_modules
    networks:
      - goldberg_network
    command: sh -c "npm run dev"

  mysql:
    image: mysql:latest
    container_name: goldberg_mysql
    restart: unless-stopped
    env_file: .env
    environment:
      # MYSQL_DATABASE: 'goldberg'
      - MYSQL_USER=web
      - MYSQL_PASSWORD=web
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13000:3306
    volumes:
      - my-db:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - goldberg_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: goldberg_rabbitmq
    ports:
        - 14000:5672
        - 15000:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq
    extra_hosts:
      - "host.docker.internal:192.168.1.113"

  mqsender:
    container_name: goldberg_mqsender
    build:
      context: ..
      dockerfile: ./env/mqsender.Dockerfile
    ports:
      - 16000:3000
    expose:
      - 3000
    volumes:
      - ../mqsender:/usr/src/app
      - mqsender_node_modules:/usr/src/app/node_modules
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq
      - goldberg_network
    command: npm run dev

networks:
  goldberg_network:
    driver: bridge
  rabbitmq:
    driver: bridge
volumes:
  client_node_modules:
  mqsender_node_modules:
  my-db: