version: '3.4'
services:
  api:
    container_name: goldberg_api
    build: 
        context: ..
        dockerfile: ./env/api.Dockerfile
        args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports: 
      - 11000:80
    volumes:
      - ../api:/var/www/html
    env_file:
      - ./.env
    networks:
      - goldberg_network

  client:
    container_name: goldberg_client
    build: 
      context: ..
      dockerfile: ./env/client.Dockerfile
    ports:
      - 12000:5173
    env_file:
      - .env
    volumes:
      - ../client:/app
      - /app/node_modules
    networks:
      - goldberg_network
    command: npm run dev
networks:
  goldberg_network:
      driver: bridge
volumes:
  node_modules: